const MODS = [
  "Accessories",
  "Allhallows Mod",
  "AmbientSounds 6",
  "Amendments",
  "AppleSkin",
  "Architectury API",
  "Artifacts",
  "Backpacked",
  "Balm (Fabric Edition)",
  "Beautify",
  "Better Archeology",
  "Better Clouds",
  "Better Third Person",
  "BetterF3",
  "Biolith",
  "BiomeSpy",
  "Bookshelf",
  "Brewin' And Chewin'",
  "CIT Resewn",
  "Carry On",
  "Christmas Culinary & Decorations",
  "ClickThrough Plus",
  "Cloth Config v15",
  "Clumps",
  "Clutter",
  "Collective",
  "Configured",
  "Continuity",
  "Controlling",
  "Convenient Decor",
  "Cookies, Candy and Cakes",
  "Copper Age Backport",
  "Crash Assistant",
  "CreativeCore",
  "Cristel Lib",
  "Critters and Companions",
  "Cull Leaves",
  "Cupboard",
  "Cursors Extended",
  "Display Delight [Fabric]",
  "Dungeons and Taverns",
  "Dusty Decorations Refabricated",
  "Eating Animation [Fabric]",
  "EnchantmentDescriptions",
  "Entity Culling Fabric/Forge",
  "Entity Model Features",
  "Entity Texture Features",
  "Explorer's Compass",
  "Explorify – Dungeons & Structures",
  "Exposure",
  "Fabric API",
  "Fabric Language Kotlin",
  "Falling Leaves",
  "FallingTree",
  "Farmer's Delight",
  "Farmers Structures",
  "FerriteCore",
  "Field Guide",
  "Forge Config API Port",
  "Formations (Structure Library)",
  "Formations Nether",
  "Formations Overworld",
  "Framework",
  "Freecam",
  "Fzzy Config",
  "GeckoLib 4",
  "Genshin Instruments",
  "Ghosts",
  "GlitchCore",
  "Goblin Traders",
  "Golem Overhaul",
  "Good Ending",
  "Handcrafted",
  "Hobbit Hill Village",
  "Horseman",
  "Immersive Overlays",
  "Inventory Essentials",
  "Iris Shaders",
  "Item Descriptions",
  "Jade 🔍",
  "JamLib",
  "Just Another Rotten Flesh to Leather Mod",
  "Just Enough Items",
  "Kaleidoscope Cookery",
  "Lavender",
  "LibJF",
  "Lilis' Lucky Lures",
  "Loot Journal: Pickup Notifier [Fabric Edition]",
  "M.R.U",
  "Macaw's Holidays",
  "Macaw's Paintings",
  "Magic Vibe Decorations",
  "MidnightLib",
  "Mod Menu",
  "ModernFix",
  "Moonlight Lib",
  "More Delight",
  "Mouse Tweaks",
  "Mystic's Biomes",
  "Nature's Compass",
  "Night Lights",
  "Not Enough Recipe Book",
  "NotEnoughAnimations",
  "Patchouli (Fabric/Quilt)",
  "Paxi",
  "Peaceful Hunger",
  "Peaceful Progression",
  "Placeholder API",
  "Platform",
  "Polytone",
  "Prickle",
  "Reese's Sodium Options",
  "Resourceful Config",
  "Resourceful Lib",
  "Respackopts",
  "Ribbits",
  "RightClickHarvest",
  "Rustic Delight",
  "Scholar",
  "Searchables",
  "Serene Seasons",
  "ShatterLib | OctoLib",
  "Sit",
  "Skin Layers 3D",
  "Sodium",
  "Sodium Options API",
  "Sodium/Embeddium Extras",
  "Sounds",
  "SoundsBeGone",
  "SparseStructures",
  "Spyglass Improvements",
  "Storage Delight",
  "Structurify",
  "Supplementaries",
  "Supplementaries Squared",
  "TerraBlender (Fabric)",
  "Tidal Towns",
  "Towns and Towers",
  "Trek",
  "Trinkets",
  "VanillaBackport",
  "Vegan Delight",
  "Villager Names",
  "WI Zoom",
  "Waystones",
  "Xaero's Minimap",
  "Xaero's World Map",
  "YUNG's API",
  "YetAnotherConfigLib",
  "[Let's Do Addon] Compat",
  "[Let's Do] API",
  "[Let's Do] Bakery",
  "[Let's Do] BloomingNature",
  "[Let's Do] Brewery",
  "[Let's Do] Candlelight",
  "[Let's Do] Farm & Charm",
  "[Let's Do] Furniture",
  "[Let's Do] HerbalBrews",
  "[Let's Do] LilisPottery",
  "[Let's Do] Meadow",
  "[Let's Do] Vinery",
  "[Let's Do] WilderNature",
  "[Let's Do] Camping",
  "choppersdelight",
  "oωo",
  "playerAnimator"
];

const grid = document.getElementById('mods-grid');
const searchInput = document.getElementById('mods-search');
const emptyMsg = document.getElementById('mods-empty');
const countEl = document.getElementById('mods-count');

if (countEl) countEl.textContent = MODS.length;

function renderMods(list) {
  grid.innerHTML = '';
  if (list.length === 0) {
    emptyMsg.hidden = false;
    return;
  }
  emptyMsg.hidden = true;
  const frag = document.createDocumentFragment();
  list.forEach((name) => {
    const li = document.createElement('li');
    li.className = 'mod-pill';
    li.textContent = name;
    frag.appendChild(li);
  });
  grid.appendChild(frag);
}

renderMods(MODS);

if (searchInput) {
  searchInput.addEventListener('input', () => {
    const q = searchInput.value.trim().toLowerCase();
    const filtered = q
      ? MODS.filter((name) => name.toLowerCase().includes(q))
      : MODS;
    renderMods(filtered);
  });
}
